version: '3.8'

services:
  vidgenix-dev:
    build:
      context: .
      target: deps
      args:
        NEXT_PUBLIC_CLERK_PUBLISHABLE_KEY: ${NEXT_PUBLIC_CLERK_PUBLISHABLE_KEY}
        CLERK_SECRET_KEY: ${CLERK_SECRET_KEY}
        GROQ_API_KEY: ${GROQ_API_KEY}
        DEEPGRAM_API_KEY: ${DEEPGRAM_API_KEY}
        IMAGE_GENERATION_API_URL: ${IMAGE_GENERATION_API_URL}
    volumes:
      - .:/app
      - /app/node_modules
      - /app/.next
      - video-processing:/app/public/generated
    ports:
      - "3000:3000"
    env_file:
      - .env.docker
    command: pnpm dev

  vidgenix-prod:
    build:
      context: .
      target: runner
      args:
        NEXT_PUBLIC_CLERK_PUBLISHABLE_KEY: ${NEXT_PUBLIC_CLERK_PUBLISHABLE_KEY}
        CLERK_SECRET_KEY: ${CLERK_SECRET_KEY}
        GROQ_API_KEY: ${GROQ_API_KEY}
        DEEPGRAM_API_KEY: ${DEEPGRAM_API_KEY}
        IMAGE_GENERATION_API_URL: ${IMAGE_GENERATION_API_URL}
    ports:
      - "3000:3000"
    volumes:
      - video-processing:/app/public/generated
    env_file:
      - .env.docker

volumes:
  video-processing:
