[phases.setup]
nixPkgs = [
    "nodejs_20",
    "npm",
    "ffmpeg-full",
    "x264",
    "x265",
    "fdk_aac",
    "chromium",
    "glibc",
    "glib",
    "nss",
    "nspr",
    "atk",
    "at-spi2-atk",
    "libdrm",
    "mesa",
    "expat",
    "cups",
    "dbus",
    "gtk3",
    "pango",
    "cairo"
]

[phases.setup.env]
PUPPETEER_SKIP_CHROMIUM_DOWNLOAD = "true"
CHROME_BIN = "/nix/store/chromium-unwrapped/bin/chromium"
PUPPETEER_EXECUTABLE_PATH = "/nix/store/chromium-unwrapped/bin/chromium"

[phases.build]
resourceLimits = { memory = "3500M", swap = "1G" }

[phases.install]
cmds = ["npm install -g corepack@0.24.1", "corepack enable"]