[phases.setup]
nixPkgs = [
    "nodejs-20_x",
    "ffmpeg-full",
    "x264",
    "x265", 
    "fdk_aac",
    "chromium",
    "glibc",
    "glib",
    "nss",
    "nspr",
    "atk",
    "at-spi2-atk",
    "libdrm",
    "mesa",
    "expat",
    "cups",
    "dbus",
    "gtk3",
    "pango",
    "cairo"
]

[phases.setup.env]
PUPPETEER_SKIP_CHROMIUM_DOWNLOAD = "true"
CHROME_BIN = "/nix/store/chromium/bin/chromium"
PUPPETEER_EXECUTABLE_PATH = "/nix/store/chromium/bin/chromium"

[phases.install]
cmds = [
    "corepack enable",
    "pnpm install --frozen-lockfile"
]

[phases.build]
cmds = ["pnpm run build"]
resourceLimits = { memory = "3500M", swap = "1G" }

[start]
cmd = "pnpm run start"